---
title: "WritingExercise02"
---

# Instructions

Each of the writing samples below violates at least one of Strunk and White’s Principles of Composition. Read the samples critically, and edit to improve them. Remember to make a commit to save your changes when you are done. 

# Writing Samples

## Principle: use the active voice

An analysis was performed by scientists to understand the metabolic pathways in bacteria.

## Put statements in positive form.

Bacteria that are able to metabolize glucose are important for fermentation.

## Use definite, specific, concrete language.

studies indicate that algae is useful in biofuel production.

## Omit needless words
studies show the metabolic pathways of *Aspergillus niger* can be engineered to enhance production of citric acid nedded for indusstial processes

## Express coordinate ideas in similar form.

Microbes are used to produce a range of fermented foods: yeast to produce bread and alcoholic products including beer, wine and sake. bacillus is used to produce natto, cheese, fermented vegetables, and pickles made by lactic acid bacteria; fermentation is even important for production of coffee and chocolate. 

## Keep related words together.
microbes such as ideonella sakaiensis are able to dgerade plastic such as polyethenr using specific enzyems such as PETase undre specifc eniromental conditions and after appropriate pre-treatment of the substarate 

## In summaries, keep to one tense.

The engineered *E. coli* strain was grown in a 5 L bioreactor for 24 hours. 
During this period, the glucose concentration decreased steadily, while the optical density increases from 0.2 to 8.4. At the end of the fermentation, the culture was harvested by centrifugation and the recombinant enzyme purified using affinity chromatography. 
The purified enzyme showed a specific activity of 42 U/mg and was suitable for use in the subsequent biocatalytic process.

## Place the emphatic words of a sentence at the end.

genomic data suggests that any species of streptomyces produce a variety of antibiotics 

